name       : lpeg
version    : 1.0.0
release    : 1
source     :
    - http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.0.tar.gz : 10190ae758a22a16415429a9eb70344cf29cbda738a6962a9f94a732340abf8e
license    : MIT
component  : programming
summary    : Pattern-matching library for Lua 5.1
description: |
    Pattern-matching library for Lua 5.1
builddeps  :
    - pkgconfig(lua-5.1)
build      : |
    %make
install    : |
    install -Dm644 lpeg.so "$installdir"/%libdir%/lua/5.1/lpeg.so
    install -Dm644 re.lua "$installdir"/usr/share/lua/5.1/re.lua
