name       : lpeg
version    : 1.0.1
release    : 2
source     :
    - http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.1.tar.gz : 62d9f7a9ea3c1f215c77e0cadd8534c6ad9af0fb711c3f89188a8891c72f026b
license    : MIT
component  : programming
summary    : Pattern-matching library for Lua 5.3
description: |
    Pattern-matching library for Lua 5.3
builddeps  :
    - pkgconfig(lua-5.3)
build      : |
    %make
install    : |
    install -Dm644 lpeg.so "$installdir"/%libdir%/lua/5.3/lpeg.so
    install -Dm644 re.lua "$installdir"/usr/share/lua/5.3/re.lua
