name       : lpeg
version    : 1.0.1
release    : 3
source     :
    - http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.1.tar.gz : 62d9f7a9ea3c1f215c77e0cadd8534c6ad9af0fb711c3f89188a8891c72f026b
license    : MIT
component  : programming
summary    : Pattern-matching library for Lua 5.1 and 5.3
description: |
    Pattern-matching library for Lua 5.1 and 5.3
builddeps  :
    - pkgconfig(lua-5.1)
    - pkgconfig(lua-5.3)
setup      : |
    builddir=${PWD##*/}
    cd ..
    cp -a $builddir lpeg-lua51
    mv $builddir lpeg-lua53
build      : |
    %make -C lpeg-lua51 LUADIR=/usr/include/lua5.1
    %make -C lpeg-lua53 LUADIR=/usr/include
install    : |
    pushd lpeg-lua51
        install -Dm00644 lpeg.so "$installdir"/%libdir%/lua/5.1/lpeg.so
        install -Dm00644 re.lua "$installdir"/usr/share/lua/5.1/re.lua
    popd
    pushd lpeg-lua53
        install -Dm00644 lpeg.so "$installdir"/%libdir%/lua/5.3/lpeg.so
        install -Dm00644 re.lua "$installdir"/usr/share/lua/5.3/re.lua
    popd
check     : |
    pushd lpeg-lua51
        lua5.1 test.lua
    popd
    pushd lpeg-lua53
        lua test.lua
    popd
